
# netlify.toml - Configuration file for Netlify deployments

[build]
  # The directory to publish (relative to root of your repo)
  publish = "dist"
  # The build command
  command = "npm run build"

# Redirects and rewrites
[[redirects]]
  # Redirect any path that doesn't exist to index.html with a 200 status code
  from = "/*"
  to = "/index.html"
  status = 200

# Headers to set on all assets
[[headers]]
  # Define which paths this specific [[headers]] block will cover
  for = "/*"
    [headers.values]
    # Cache control settings
    Cache-Control = "public, max-age=0, must-revalidate"

# For static assets like images, scripts, and styles
[[headers]]
  for = "/assets/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
